<?php
return [
	'news/ajaxlist/<type:.+>/<id:.+>/<page:.+>/<last:.+>'=>'news/ajaxlist',
	'news/detail/<id:.+>'=>'news/detail',
	'news/<type:.+>/<id:.+>'=>'news/index',
	'resource/download/<type:.+>/<ids:.+>'=>'resource/download',
	//英文版本路由
	'en'=>'site/index',
	'en/site'=>'site/index',
	'en/about'=>'about/index',
	'en/application/media'=>'application/media',
	'en/application/person'=>'application/person',
	'en/application/company'=>'application/company',
	'en/application/doapply'=>'application/doapply',
	'en/download'=>'download/index',
	'en/forum'=>'forum/index',
	'en/forum/detail'=>'forum/detail',
	'en/meeting'=>'meeting/index',
	'en/news/ajaxlist/<type:.+>/<id:.+>/<page:.+>/<last:.+>'=>'news/ajaxlist',
	'en/news/detail/<id:.+>'=>'news/detail',
	'en/news'=>'news/index',
	'en/news/<type:.+>/<id:.+>'=>'news/index',
	'en/resource/download/<type:.+>/<ids:.+>'=>'resource/download',
];